---
title: "Fukuoka COVID-19 Dashboard"
output: 
  flexdashboard::flex_dashboard:
    social: [ "menu" ]
    source_code: "https://github.com/kzktmr/Covid19Dashboard"
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
# ライブラリ
library(tidyr)
library(dplyr)
library(purrr)
library(readr)
library(stringr)
library(lubridate)
library(RcppRoll)
library(flexdashboard)
library(highcharter)
library(DT)
library(geojsonio)

# オプション
hcopts <-  getOption("highcharter.lang")
hcopts$thousandsSep <- ","
options(highcharter.lang = hcopts)

# データ
population  <- read_csv("data/population.csv")
newlycases  <- read_csv("data/newlycases.csv")
patients    <- read_csv("data/patients.csv") %>% mutate(untraceable = 1)
inspection  <- read_csv("data/inspection.csv")
situation   <- read_csv("data/situation.csv") %>%
  bind_rows(read_csv("data/situation2.csv")) %>% drop_na()
sickbeds    <- read_csv("data/sickbeds.csv") %>% 
  add_row(date = Sys.Date()) %>% complete(date = full_seq(date, 1)) %>%
  fill(-date) %>% distinct()
vaccination <- read_csv("data/vaccination.csv")
severe_cases<- read_csv("data/severe_cases.csv")
transport   <- read_csv("data/emergency_transport.csv")
age_pop     <- read_csv("data/population_by_age.csv")
region      <- read_csv("data/fukuoka_region.csv")
map         <- geojson_read("data/map.geojson")

# 定数
pref_pop <- population %>% filter(name == "県") %>% pull()
age_pop2 <- tibble(age = c("TTL", "65-"), pop = c(5123371, 1405740))

# 関数
last_value <- function(dat, col){
  col <- enquo(col)
  dat %>% select(!!col) %>% tail(1) %>% pull()
}
md <- function(x){
  str_c(lubridate::month(x), "/", lubridate::day(x))
}
pop <- function(city){
  city_pop %>% filter(name == city) %>% pull(population)
}
fmt <- function(x){
  x <- sprintf("%.1f", x) %>% str_split("\\.") %>% unlist()
  x <- format(as.integer(x[1]), big.mark = ",") %>% str_c(x[2], sep = ".")
  return(x)
}
```


ステージ判断指標
=====================================  

Row
-----------------------------------------------------------------------

### 新規感染者数
```{r}
detected <- newlycases %>% 
  mutate(detected_sum = roll_sumr(detected, 7),
         increase = detected_sum > lag(detected_sum),
         value = detected_sum / pref_pop * 1e5,
         date = as.Date(date)) %>% 
  filter(date >= as.Date("2021-01-01")) %>% 
  select(date, value, increase)
detected_value <- detected %>% last_value(value)
detected_increase <- detected %>% last_value(increase)
valueBox(fmt(detected_value), 
         caption = "10万人あたり週間新規感染者数（人）",
         icon = ifelse(detected_increase, "fa-arrow-up", "fa-arrow-down"),
         color = ifelse(detected_value >= 25, "danger", 
                        ifelse(detected_value >= 15, "warning", "primary"))
         )
```

### 感染経路不明割合
```{r}
untraceable <- patients %>% 
  group_by(date, untraceable) %>% summarise(n = n()) %>% ungroup() %>% 
  mutate(untraceable = if_else(is.na(untraceable), "traceable", "untraceable")) %>% 
  pivot_wider(names_from = untraceable, values_from = n, values_fill = 0) %>% 
  complete(date = full_seq(date, 1), fill = list(untraceable = 0, traceable = 0)) %>% 
  mutate(n = rowSums(across(where(is.numeric))), sum_n = roll_sumr(n, 7),
         sum_u = roll_sumr(untraceable, 7), value = sum_u / sum_n * 100,
         increase = value > lag(value),
         date = as.Date(date)) %>% 
  select(date, value, increase) %>% filter(date >= as.Date("2021-01-01"))
untraceable_value <- untraceable %>% last_value(value)
untraceable_increase <- untraceable %>% last_value(increase)
valueBox(sprintf("%.1f", untraceable_value), 
         caption = "感染経路不明割合（％）",
         icon = ifelse(untraceable_increase, "fa-arrow-up", "fa-arrow-down"),
         color = ifelse(untraceable_value >= 50, "danger", "primary"))
```

### 検査等陽性率
```{r}
positive_ratio <- situation %>% 
  filter(name %in% c("陽性者数累計（疑似症患者を除く）", "陽性者数累計")) %>% 
  mutate(detected_sum = value - lag(value, 7)) %>% left_join(inspection) %>% 
  mutate(inspected_sum = roll_sumr(inspected, 7),
         value = detected_sum / inspected_sum * 100,
         increase = value > lag(value),
         date = as.Date(date)) %>% 
  select(date, value, increase) %>% filter(date >= as.Date("2021-01-01"))
positive_ratio_value <- positive_ratio %>% last_value(value)
positive_ratio_increase <- positive_ratio %>% last_value(increase)
valueBox(sprintf("%.1f", positive_ratio_value), 
         caption = "検査等陽性率（％）",
         icon = ifelse(positive_ratio_increase, "fa-arrow-up", "fa-arrow-down"),
         color = ifelse(is.na(positive_ratio_value), "info",
                        ifelse(positive_ratio_value >= 10, "danger", 
                               ifelse(positive_ratio_value >= 5, "warning", "primary")))
         )
```

Row
-----------------------------------------------------------------------

### 療養者数
```{r}
total_patient <-
  situation %>% filter(str_detect(name, "者の数$")) %>% 
  group_by(date) %>% summarise(value = sum(value)) %>% ungroup() %>% 
  mutate(increase = value > lag(value),
         value = value / pref_pop * 1e5,
         date = as.Date(date)) %>% drop_na() %>% 
  select(date, value, increase) %>% filter(date >= as.Date("2021-01-01"))
total_patient_value <- total_patient %>% last_value(value)
total_patient_increase <- total_patient %>% last_value(increase)
valueBox(fmt(total_patient_value), 
         caption = "10万人あたり療養者数（人）",
         icon = ifelse(total_patient_increase, "fa-arrow-up", "fa-arrow-down"),
         color = ifelse(total_patient_value >= 30, "danger", 
                        ifelse(total_patient_value >= 20, "warning", "primary"))
         )
```

### 確保病床使用率
```{r}
bed_occupancy <- situation %>% 
  filter(name == "うち確保病床の入院者数") %>% 
  filter(date >= "2021-01-01") %>% left_join(sickbeds) %>% na.omit() %>% 
  mutate(value = value / bed * 100, 
         increase = value > lag(value),
         date = as.Date(date)) %>% 
  select(date, value, increase) %>% filter(date >= as.Date("2021-01-01"))

bed_occupancy_value = bed_occupancy %>% last_value(value)
bed_occupancy_increase = bed_occupancy %>% last_value(increase)
valueBox(sprintf("%.1f", bed_occupancy_value), 
         caption = "確保病床使用率（％）",
         icon = ifelse(bed_occupancy_increase, "fa-arrow-up", "fa-arrow-down"),
         color = ifelse(bed_occupancy_value >= 50, "danger", 
                        ifelse(bed_occupancy_value >= 20, "warning", "primary"))
         )
```

### 入院率
```{r}
hospital_ratio <- situation %>% 
  filter(str_detect(name, "者の数$")) %>% 
  pivot_wider() %>% 
  mutate(value = `入院中の者の数` / (`入院中の者の数` + `宿泊療養中の者の数` + `自宅待機等の者の数`) * 100,
         increase = value > lag(value),
         date = as.Date(date)) %>% 
  filter(date >= as.Date("2021-01-01")) %>% na.omit()
hospital_ratio_value <- hospital_ratio %>% last_value(value)
hospital_ratio_increase <- hospital_ratio %>% last_value(increase)
valueBox(sprintf("%.1f", hospital_ratio_value), 
         caption = "入院率（％）",
         icon = ifelse(hospital_ratio_increase, "fa-arrow-up", "fa-arrow-down"),
         color = ifelse(hospital_ratio_value <= 25, "danger", 
                        ifelse(hospital_ratio_value <= 40, "warning", "primary"))
         )
```

Row
-----------------------------------------------------------------------

### 10万人あたり週間新規感染者数（人）

```{r}
detected %>% filter(date >= max(date) - 365) %>% 
  hchart("line", hcaes(x = date, y = value)) %>% 
  hc_yAxis(title = FALSE,
           labels = list(
             format = "{value:,.0f}"
           ),
           plotLines = list(
             list(value = 25, color = "#ff0000", width = 1),
             list(value = 15, color = "#ffa500", width = 1)
             )
           ) %>%
  hc_xAxis(title = FALSE) %>%
  hc_tooltip(pointFormat = "<b>{point.value:,.1f}</b> 人") %>% 
  hc_chart(zoomType = "x",
           resetZoomButton = list(
             position = list(align = "left")
             )
           ) %>% 
  hc_exporting(enabled = TRUE)
```

### 感染経路不明割合（％）

```{r}
untraceable %>% filter(date >= max(date) - 365) %>%
  hchart("line", hcaes(x = date, y = value,)) %>% 
  hc_yAxis(title = FALSE,
           min = 0,
           plotLines = list(
             list(value = 50, color = "#ff0000", width = 1)
             )
           ) %>% 
  hc_xAxis(title = FALSE) %>% 
  hc_tooltip(pointFormat = "<b>{point.value:.1f}</b> %") %>% 
  hc_chart(zoomType = "x",
           resetZoomButton = list(
             position = list(align = "left")
             )
           ) %>% 
  hc_exporting(enabled = TRUE)
```

### 検査等陽性率（％）

```{r}
positive_ratio %>% filter(date >= max(date) - 365) %>%
  hchart("line", hcaes(x = date, y = value,)) %>% 
  hc_yAxis(title = FALSE,
           plotLines = list(
             list(value = 10, color = "#ff0000", width = 1),
             list(value = 5, color = "#ffa500", width = 1)
             )
           ) %>% 
  hc_xAxis(title = FALSE) %>% 
  hc_tooltip(pointFormat = "<b>{point.value:.1f} </b>%") %>% 
  hc_chart(zoomType = "x",
           resetZoomButton = list(
             position = list(align = "left")
             )
           ) %>% 
  hc_exporting(enabled = TRUE)
```

Row
-----------------------------------------------------------------------

### 10万人あたり療養者数

```{r}
total_patient %>% filter(date >= max(date) - 365) %>%
  hchart("line", hcaes(x = date, y = value,)) %>% 
  hc_yAxis(title = FALSE,
           labels = list(
             format = "{value:,.0f}"
           ),
           plotLines = list(
             list(value = 30, color = "#ff0000", width = 1),
             list(value = 20, color = "#ffa500", width = 1)
             )
           ) %>% 
  hc_xAxis(title = FALSE) %>% 
  hc_tooltip(pointFormat = "<b>{point.value:,.1f}</b> 人") %>% 
  hc_chart(zoomType = "x",
           resetZoomButton = list(
             position = list(align = "left")
             )
           ) %>% 
  hc_exporting(enabled = TRUE)
```

### 確保病床使用率（％）
```{r}
bed_occupancy %>% filter(date >= max(date) - 365) %>%
  hchart("line", hcaes(x = date, y = value,)) %>% 
  hc_yAxis(title = FALSE,
           plotLines = list(
             list(value = 50, color = "#ff0000", width = 1),
             list(value = 20, color = "#ffa500", width = 1)
             )
           ) %>% 
  hc_xAxis(title = FALSE) %>% 
  hc_tooltip(pointFormat = "<b>{point.value:.1f} </b>%") %>% 
  hc_chart(zoomType = "x",
           resetZoomButton = list(
             position = list(align = "left")
             )
           ) %>% 
  hc_exporting(enabled = TRUE)
```

### 入院率（％）
```{r}
hospital_ratio %>% filter(date >= max(date) - 365) %>%
  hchart("line", hcaes(x = date, y = value,)) %>% 
  hc_yAxis(title = FALSE,
           plotLines = list(
             list(value = 25, color = "#ff0000", width = 1),
             list(value = 40, color = "#ffa500", width = 1)
             )
           ) %>% 
  hc_xAxis(title = FALSE) %>% 
  hc_tooltip(pointFormat = "<b>{point.value:.1f}</b> %") %>% 
  hc_chart(zoomType = "x",
           resetZoomButton = list(
             position = list(align = "left")
             )
           ) %>% 
  hc_exporting(enabled = TRUE)
```

ワクチン接種状況
=====================================  

```{r include=FALSE}
vaccination_rate <-
  vaccination %>% #filter(age != "UNK") 
  group_by(date, age, status) %>% summarise(count = sum(count), .groups = "keep") %>% 
  ungroup(age) %>% 
  summarise(add_row(cur_data(), age = "TTL", count = sum(count))) %>% 
  filter(age %in% c("65-", "TTL")) %>% 
  group_by(age, status) %>% 
  mutate(cum_sum = cumsum(count)) %>% 
  left_join(age_pop2) %>% 
  mutate(ratio =  cum_sum/ pop * 100) %>% ungroup() %>% 
  mutate(date = as.Date(date), 
         age = factor(age, labels = c("高齢", "全体"), levels = c("65-", "TTL")),
         status = factor(status, labels = c("1回目", "2回目", "3回目", "4回目"))) %>% 
  unite("status", age:status, sep = "") %>% 
  arrange(date) 
```

Row
-----------------------------------------------------------------------

### 接種率（高齢者，2回目）
```{r}
elder_1st <- vaccination_rate %>% 
  filter(status == "高齢2回目") %>% last_value(ratio)
gauge(sprintf("%.1f", elder_1st), min = 0, max = 100, symbol = '%')
```

### 接種率（高齢者，3回目）
```{r}
elder_2nd <- vaccination_rate %>% 
  filter(status == "高齢3回目") %>% last_value(ratio)
gauge(sprintf("%.1f", elder_2nd), min = 0, max = 100, symbol = '%')
```

### 接種率（高齢者，4回目）
```{r}
elder_3rd <- vaccination_rate %>% 
  filter(status == "高齢4回目") %>% last_value(ratio)
gauge(sprintf("%.1f", elder_3rd), min = 0, max = 100, symbol = '%')
```

### 接種率（全人口，2回目）
```{r}
total_1st <- vaccination_rate %>% 
  filter(status == "全体2回目") %>% last_value(ratio)
gauge(sprintf("%.1f", total_1st), min = 0, max = 100, symbol = '%')
```

### 接種率（全人口，3回目）
```{r}
total_2nd <- vaccination_rate %>% 
  filter(status == "全体3回目") %>% last_value(ratio)
gauge(sprintf("%.1f", total_2nd), min = 0, max = 100, symbol = '%')
```

### 接種率（全人口，4回目）
```{r}
total_3rd <- vaccination_rate %>% 
  filter(status == "全体4回目") %>% last_value(ratio)
gauge(sprintf("%.1f", total_3rd), min = 0, max = 100, symbol = '%')
```

Row
-------------------------
### 接種回数の推移
```{r}
vaccination %>% 
  group_by(date, age, status) %>% summarise(count = sum(count)) %>% ungroup() %>% 
  mutate(date = as.Date(date), 
         age = factor(age, labels = c("65歳未満", "65歳以上", "年齢不明")),
         status = factor(status, labels = c("1回目", "2回目", "3回目", "4回目"))) %>% 
  unite("status", age:status, sep = "") %>% 
  filter(date >= max(date) - 365) %>%
  hchart("column", hcaes(x = date, y = count, group = status), 
         zoomType = "xy",
         colorKey = "status") %>% 
  hc_xAxis(title = FALSE) %>% 
  hc_yAxis(title = FALSE) %>% 
  hc_plotOptions(column = list(stacking = "normal", borderWidth = 0),
                 series = list(pointPadding = 0, groupPadding = 0)) %>% 
  hc_tooltip(pointFormat = '<span style="color:{series.color}">●</span> {series.name}:<b> {point.count:,.0f}</b>') %>% 
  hc_chart(zoomType = "x",
           resetZoomButton = list(
             position = list(align = "left")
             )
           ) %>% 
  hc_exporting(enabled = TRUE)
```

### 接種率の推移（％）
```{r}
vaccination_rate %>% 
  filter(date >= max(date) - 365) %>%
  hchart("line", hcaes(x = date, y = ratio, group = status), 
         zoomType = "x",
         colorKey = "status") %>% 
  hc_xAxis(title = FALSE) %>% 
  hc_yAxis(title = FALSE) %>% 
  hc_tooltip(pointFormat = '<span style="color:{series.color}">●</span> {series.name}:<b> {point.ratio:.1f} %</b>') %>% 
  hc_chart(zoomType = "x",
           resetZoomButton = list(
             position = list(align = "left")
             )
           ) %>% 
  hc_exporting(enabled = TRUE)
```

その他の指標①
=====================================  

Rows
-------------------------------------

### 新規陽性者数（人）
```{r}
newlycases %>%
  select(date, value = detected) %>% 
  mutate(ma = roll_meanr(value, 7)) %>% 
  filter(date >= max(date) - 365) -> tmp
hchart(tmp, "column", hcaes(x = date, y = value), name = "新規陽性者数") %>% 
  hc_xAxis(title = FALSE) %>% 
  hc_yAxis(title = FALSE) %>% 
  hc_plotOptions(column = list(stacking = "normal", borderWidth = 0),
                 series = list(pointPadding = 0, groupPadding = 0)) %>% 
    hc_tooltip(pointFormat = '<span style="color:{series.color}">●</span> {series.name}:<b> {point.value:,.0f}</b> 人') %>% 
  hc_add_series(tmp, "line", hcaes(x = date, y = ma), color = "darkblue", name = "移動平均",
                dashStyle = "shortdash",
                tooltip = list(pointFormat = '<span style="color:{series.color}">●</span> {series.name}:<b> {point.ma:,.1f}</b> 人')) %>% 
  hc_chart(zoomType = "x",
           resetZoomButton = list(
             position = list(align = "left")
             )
           ) %>% 
  hc_exporting(enabled = TRUE)
```

### PCR等検査件数（件）
```{r}
inspection %>% 
  select(date, value = inspected) %>% 
  mutate(ma = roll_meanr(value, 7)) %>% 
  filter(date >= max(date) - 365) -> tmp
tmp %>% hchart("column", hcaes(x = date, y = value), name = "PCR等検査数") %>% 
  hc_xAxis(title = FALSE) %>% 
  hc_yAxis(title = FALSE) %>% 
  hc_plotOptions(column = list(stacking = "normal", borderWidth = 0),
                 series = list(pointPadding = 0, groupPadding = 0)) %>% 
    hc_tooltip(pointFormat = '<span style="color:{series.color}">●</span> {series.name}:<b> {point.value:,.0f}</b> 件') %>% 
  hc_add_series(tmp, "line", hcaes(x = date, y = ma), color = "darkblue", name = "移動平均",
                dashStyle = "shortdash",
                tooltip = list(pointFormat = '<span style="color:{series.color}">●</span> {series.name}:<b> {point.ma:,.1f}</b> 件')) %>% 
  hc_chart(zoomType = "x",
           resetZoomButton = list(
             position = list(align = "left")
             )
           ) %>% 
  hc_exporting(enabled = TRUE)
```

Rows
-------------------------------------

### 新規感染者数の先週今週比
```{r}
newlycases %>% 
  mutate(detected_sum = roll_sumr(detected, 7),
         value = detected_sum / lag(detected_sum, 7)) %>% 
  select(date, value) %>% 
  filter(date >= max(date) - 365) %>%
  hchart("line", hcaes(x = date, y = value), name = "先週今週比") %>% 
  hc_xAxis(title = FALSE) %>% 
  hc_yAxis(title = FALSE, 
           plotLines = list(
             list(value = 1, color = "#000000", width = 1)
             )) %>% 
  hc_plotOptions(column = list(stacking = "normal", borderWidth = 0),
                 series = list(pointPadding = 0, groupPadding = 0)) %>% 
    hc_tooltip(pointFormat = '<span style="color:{series.color}">●</span> {series.name}:<b> {point.value:,.2f}</b>') %>% 
  hc_chart(zoomType = "x",
           resetZoomButton = list(
             position = list(align = "left")
             )
           ) %>% 
  hc_exporting(enabled = TRUE)
```

### 週間新規感染者の若者割合（％）
```{r}
patients %>% 
  filter(age != "調査中", age != "-") %>% 
  group_by(date, age) %>% summarise(n = n()) %>% ungroup() %>% 
  pivot_wider(names_from = age, values_from = n, values_fill = 0) %>% 
  rowwise() %>% mutate(合計 = sum(c_across(-date))) %>% 
  complete(date = full_seq(date, 1)) %>% 
  mutate(across(-date, replace_na, 0)) %>% 
  mutate(across(-date, roll_sumr, n = 7)) %>% 
  mutate(value = (`20代` + `30代`) / 合計 * 100) %>% 
  select(date, value) %>% filter(date >= max(date) - 365) %>%
  hchart("line", hcaes(x = date, y = value), name = "若者割合") %>% 
  hc_xAxis(title = FALSE) %>% 
  hc_yAxis(title = FALSE) %>% 
  hc_plotOptions(column = list(stacking = "normal", borderWidth = 0),
                 series = list(pointPadding = 0, groupPadding = 0)) %>% 
    hc_tooltip(pointFormat = '<span style="color:{series.color}">●</span> {series.name}:<b> {point.value:,.1f}</b> %') %>% 
  hc_chart(zoomType = "x",
           resetZoomButton = list(
             position = list(align = "left")
             )
           ) %>% 
  hc_exporting(enabled = TRUE)
```

その他の指標②
=====================================  

Rows
-------------------------------------

### 状況別感染者数（人）
```{r}
situation %>% 
  filter(str_detect(name, "の者の数$")) %>% 
  mutate(name = str_remove(name, "の者の数$"),
         name = factor(name, levels = c("自宅待機等", "宿泊療養中", "入院中"))) %>% 
  select(date, name, value) %>% 
  filter(date >= max(date) - 365) %>%
  hchart("area", hcaes(x = date, y = value, group = name, name = date)) %>% 
  hc_xAxis(title = FALSE) %>% 
  hc_yAxis(title = FALSE) %>% 
  hc_plotOptions(area = list(stacking = "normal", borderWidth = 0)) %>% 
  hc_tooltip(valueSuffix = " 人") %>% 
  hc_chart(zoomType = "x",
           resetZoomButton = list(
             position = list(align = "left")
             )
           ) %>% 
  hc_exporting(enabled = TRUE)
```

### 感染確認数と退院および死亡数（人）
```{r}
situation %>% 
  filter(name %in% c("陽性者数累計（疑似症患者を含む）",
                     "陽性者数累計", "退院者数累計", "死亡者数累計")) %>% 
  mutate(name = str_remove(name, "（.+）$")) %>% distinct() %>% 
  pivot_wider() %>% 
  select(date, positive = `陽性者数累計`,
         discharge = 退院者数累計, dead = 死亡者数累計) %>%
  mutate(across(where(is.numeric), function(x){x - lag(x)}),
         discharge = discharge + dead,
         across(where(is.numeric), RcppRoll::roll_meanr, n = 7)) %>%
  select(date, 感染確認 = positive, `回復・死亡` = discharge) %>%
  filter(date >= max(date) - 365) %>% pivot_longer(2:3) %>%
  hchart("line", hcaes(x = date, y = value, group = name, name = date)) %>% 
  hc_xAxis(title = FALSE) %>% 
  hc_yAxis(title = FALSE, labels = list(format = "{value:,.0f}")) %>% 
  hc_tooltip(pointFormat = '<span style="color:{series.color}">●</span> {series.name}:<b> {point.value:,.1f}</b> 人') %>% 
  hc_chart(zoomType = "x",
           resetZoomButton = list(
             position = list(align = "left")
             )
           ) %>% 
  hc_exporting(enabled = TRUE)
```

Rows
-------------------------------------

### 重症者数（人）
```{r}
severe_cases %>% 
  filter(date >= max(date) - 365) %>%
  hchart("line", hcaes(x = date, y = severe_cases), name = "重傷者数") %>% 
  hc_xAxis(title = FALSE) %>% 
  hc_yAxis(title = FALSE) %>% 
  hc_tooltip(valueSuffix = " 人") %>% 
  hc_chart(zoomType = "x",
           resetZoomButton = list(
             position = list(align = "left")
             )
           ) %>% 
  hc_exporting(enabled = TRUE)
```

### 死亡者数（人）

```{r}
situation %>% 
  filter(name == "死亡者数累計") %>%
  mutate(dead = value - lag(value),
         ma = roll_mean(dead, n = 7, fill = NA)) %>% select(-name) %>% 
  filter(date >= max(date) - 365) -> tmp
tmp %>% hchart("column", hcaes(x = date, y = dead), name = "死亡者者") %>% 
  hc_xAxis(title = FALSE) %>% 
  hc_yAxis(title = FALSE) %>% 
  hc_plotOptions(column = list(stacking = "normal", borderWidth = 0),
                 series = list(pointPadding = 0, groupPadding = 0)) %>% 
    hc_tooltip(pointFormat = '<span style="color:{series.color}">●</span> {series.name}:<b> {point.dead:,.0f}</b> 人') %>% 
  hc_add_series(tmp, "line", hcaes(x = date, y = ma), color = "darkblue", name = "移動平均",
                # dashStyle = "shortdash",
                tooltip = list(pointFormat = '<span style="color:{series.color}">●</span> {series.name}:<b> {point.ma:,.1f}</b> 人')) %>% 
  hc_chart(zoomType = "x",
           resetZoomButton = list(
             position = list(align = "left")
             )
           ) %>% 
  hc_exporting(enabled = TRUE)
```

その他の指標③
=====================================  

Rows
-------------------------------------

### 重症病床使用率（％）
```{r}
severe_cases %>% left_join(sickbeds) %>% 
  mutate(value = severe_cases / severe_bed * 100) %>% 
  select(date, value) %>% 
  filter(date >= max(date) - 365) %>%
  hchart("line", hcaes(x = date, y = value), name = "重症病床使用率") %>% 
  hc_xAxis(title = FALSE) %>% 
  hc_yAxis(title = FALSE) %>% 
    hc_tooltip(pointFormat = '<span style="color:{series.color}">●</span> {series.name}:<b> {point.value:,.1f}</b>%') %>% 
  hc_chart(zoomType = "x",
           resetZoomButton = list(
             position = list(align = "left")
             )
           ) %>% 
  hc_exporting(enabled = TRUE)
```

### 宿泊療養居室使用率（％）
```{r}
situation %>% filter(name == "宿泊療養中の者の数") %>% left_join(sickbeds) %>% 
  mutate(value = value / hotel_room * 100) %>% 
  select(date, value) %>% 
  filter(date >= max(date) - 365) %>%
  hchart("line", hcaes(x = date, y = value), name = "宿泊療養居室使用率") %>% 
  hc_xAxis(title = FALSE) %>% 
  hc_yAxis(title = FALSE) %>% 
    hc_tooltip(pointFormat = '<span style="color:{series.color}">●</span> {series.name}:<b> {point.value:,.1f}</b>%') %>% 
  hc_chart(zoomType = "x",
           resetZoomButton = list(
             position = list(align = "left")
             )
           ) %>% 
  hc_exporting(enabled = TRUE)
```

Rows
-------------------------------------

### 確保病床入院率（％）
```{r}
situation %>% 
  filter(name %in% c("入院中の者の数", "うち確保病床の入院者数")) %>% 
  pivot_wider() %>%  
  mutate(value = うち確保病床の入院者数 / 入院中の者の数 * 100) %>% 
  select(date, value) %>% 
  filter(date >= max(date) - 365) %>%
  hchart("line", hcaes(x = date, y = value), name = "確保病床入院率") %>% 
  hc_xAxis(title = FALSE) %>% 
  hc_yAxis(title = FALSE) %>% 
    hc_tooltip(pointFormat = '<span style="color:{series.color}">●</span> {series.name}:<b> {point.value:,.1f}</b>%') %>% 
  hc_chart(zoomType = "x",
           resetZoomButton = list(
             position = list(align = "left")
             )
           ) %>% 
  hc_exporting(enabled = TRUE)
```

### 救急搬送困難事案数（件）
```{r}
transport %>% filter(date >= max(date) - 365) %>% 
  hchart("line", hcaes(x = date, y = value, group = city)) %>% 
  hc_xAxis(title = FALSE) %>% 
  hc_yAxis(title = FALSE) %>% 
    hc_tooltip(pointFormat = '<span style="color:{series.color}">●</span> {series.name}:<b> {point.value:,.0f}</b>件') %>% 
  hc_chart(zoomType = "x",
           resetZoomButton = list(
             position = list(align = "left")
             )
           ) %>% 
  hc_exporting(enabled = TRUE)
```

年代別感染状況
=====================================  

Rows
-------------------------------------

### 年代別10万人あたり週間新規感染者数（人）
```{r}
patients %>% 
  filter(age != "調査中", age != "-") %>% 
  group_by(date, age) %>% summarise(n = n()) %>% ungroup() %>% 
  pivot_wider(names_from = age, values_from = n, values_fill = 0) %>% 
  complete(date = full_seq(date, 1)) %>%
  mutate(across(-date, replace_na, 0)) %>% 
  mutate(across(-date, roll_sumr, n = 7)) %>% 
  filter(date >= max(date) - 365) %>% pivot_longer(-date) %>% 
  left_join(age_pop, by = c("name" = "age10")) %>% 
  mutate(age = factor(name, levels = c("10歳未満", str_c(seq(10, 80, 10), "代"), "90代以上"), labels = str_c(seq(0, 90, 10), "~", c(seq(9, 89, 10), "")))) %>% 
  mutate(value = value * 1e5 / population) %>% arrange(date, age) %>% 
hchart("line", hcaes(x = date, y = value, group = age, name = date)) %>% 
  hc_xAxis(title = FALSE) %>% 
  hc_yAxis(title = FALSE, labels = list(format = "{value:,.0f}")) %>% 
  hc_tooltip(pointFormat = '<span style="color:{series.color}">●</span> {series.name}:<b> {point.value:,.1f}</b> 人') %>% 
  hc_chart(zoomType = "x",
           resetZoomButton = list(
             position = list(align = "left")
             )
           ) %>% 
  hc_exporting(enabled = TRUE)
```

地域別感染状況{data-orientation=columns}
=====================================  

Column
-------------------------------------

### 地域別人口10万人あたり週間新規陽性者数
```{r}
by_region <- patients %>% 
  mutate(city = case_when(str_detect(address, "^北九州市.*区") ~ 
                            str_remove(address, "北九州市"),
                          str_detect(address, "^福岡市.*区") ~ 
                            str_remove(address, "福岡市"),
                          str_detect(address, "^那珂川$") ~ "那珂川市",
                          str_detect(address, "^大野城$") ~ "大野城市",
                          str_detect(address, "^三瀦郡$") ~ "三潴郡",
                          str_detect(address, "^鞍手町$") ~ "鞍手郡",
                          str_detect(address, "^苅田町$") ~ "京都郡",
                          str_detect(address, "^大宰府市$") ~ "太宰府市",
                          str_detect(address, "^粕屋郡$") ~ "糟屋郡",
                          str_detect(address, "^若宮市$") ~ "宮若市",
                          str_detect(address, "[都道府県]$") ~ NA_character_,
                          str_detect(address, ".*県.*市") ~ NA_character_,
                          str_detect(address, 
                                     paste(c("下関市", "熊本市", "大分市", "中津市",
                                               "鳥栖市", "長崎市", "大阪市", "佐世保市",
                                               "京都市", "広島市", "裾野市", "唐津市",
                                               "鹿児島市", "倉敷市", "仙台市", "山口市",
                                               "三養基郡", "玉名郡", "荒尾市",
                                             "宮崎市", "名古屋市", "佐賀市"),
                                             collapse = "|")) ~ NA_character_,
                            str_detect(address, "海外|県外|調査中|確認中|―") ~ NA_character_,
                            address == 0 ~ NA_character_,
                            TRUE ~ address)) %>% 
  filter(!is.na(city)) %>% 
  left_join(region, by = "city")
# by_region %>% filter(is.na(county))
by_region %>% 
  group_by(date, region) %>% count() %>% ungroup() %>% 
  pivot_wider(names_from = region, values_from = n, values_fill = 0) %>% 
  complete(date = full_seq(date, 1), 
           fill = list("福岡" = 0, "北九州" = 0, "筑後" = 0, "筑豊" = 0)) %>% 
  mutate(across(where(is.numeric), roll_sumr, n = 7)) %>% 
  pivot_longer(-date) %>% mutate(name = str_c(name, "地域")) %>% 
  left_join(population) %>% mutate(value = value / population * 100000) %>%
  mutate(name = factor(name, levels = c("北九州地域", "福岡地域", "筑後地域", "筑豊地域"))) %>%
  filter(date >= max(date) - 365) %>%
  hchart("line", hcaes(x = date, y = value, group = name, name = date)) %>% 
  hc_xAxis(title = FALSE) %>% 
  hc_yAxis(title = FALSE) %>% 
  hc_tooltip(pointFormat = '<span style="color:{series.color}">●</span> {series.name}:<b> {point.value:,.1f}</b> 人') %>% 
  hc_chart(zoomType = "x",
           resetZoomButton = list(
             position = list(align = "left")
             )
           ) %>% 
  hc_exporting(enabled = TRUE)
```

### 市・区・郡別人口10万人あたり週間新規陽性者数

```{r}
tmp_data <- by_region %>% 
  select(date, county) %>% group_by(date, county) %>% count(name = "value") %>%
  group_by(county) %>% complete(date = full_seq(date, 1), fill = list(value = 0)) %>% 
  ungroup() %>% 
  pivot_wider(names_from = county, values_fill = 0) %>% arrange(date) %>% 
  mutate(福岡市 = 福岡市 + 東区 + 博多区 +中央区 +南区 + 城南区 + 早良区 + 西区,
         北九州市 = 北九州市 + 門司区 + 小倉北区 + 小倉南区 + 若松区 + 八幡東区 + 八幡西区 + 戸畑区) %>% 
  mutate(across(where(is.numeric), RcppRoll::roll_sumr, n = 7)) %>% 
  filter(date >= max(date) - 14) %>% pivot_longer(-date, names_to = "county") %>% 
  left_join(population, by = c("county" = "name")) %>% 
  mutate(n = value, value = value * 1e5 / population)
tmp_data %>% select(date, county, value, n, population) %>%
  filter(date == max(date)) %>% 
  datatable(rownames = FALSE,
            options = list(scrollY = "100%",
                           order = list(list(2, "desc")),
                           orderClasses = TRUE)) %>% 
  formatRound("value", digits = 1) %>% formatRound(c("n", "population"), digits = 0)
```

Column
-----------------------------------------------------------------------

### 市・区・郡別人口10万人あたり週間新規陽性者数

```{r}
tmp_data <- tmp_data %>% 
  mutate(date = datetime_to_timestamp(date))
cht_data <- tmp_data %>% nest(-county) %>% 
  mutate(
    data = map(data, mutate_mapping, hcaes(x = date, y = value), drop = TRUE),
    data = map(data, list_parse)
  ) %>% rename(region = county, ttdata = data)
map_data <- tmp_data %>% filter(date == max(date)) %>% rename(region = county) %>% 
  left_join(cht_data) 
  
highchart() %>%
  hc_add_series_map(map, map_data, "value", "region",
                    name = "10万人あたり週間新規感染者数",
                    dataLabels = list(enabled = TRUE, 
                                      format = '{point.properties.region}')
                    ) %>% 
  hc_colorAxis(stops = color_stops(10, colorspace::sequential_hcl(palette = "Heat", 10, rev = TRUE))) %>% 
  hc_legend(valueDecimals = 0) %>% 
  hc_tooltip(useHTML = TRUE, 
             pointFormatter = tooltip_chart(accesor = "ttdata", 
               hc_opts = list(xAxis = list(title = FALSE,
                                           type = "datetime"), 
                              yAxis = list(title = FALSE,
                                           labels = list(format = "{value:,.0f}")),
                              series = list(list(name = "",
                                                 dataLabels = list(enabled = TRUE,
                                                                   format = "{y:,.1f}"))),
                              subtitle = list(floating = TRUE, text = "point.region")
               ))) %>% 
  hc_mapNavigation(enabled = TRUE) %>% 
  hc_exporting(enabled = TRUE)
```


