name: Get Data

on:
  schedule:
    - cron: '5 0,6,12,18 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up R
        uses: r-lib/actions/setup-r@v1
      - name: Install packages 
        run: |
          install.packages(c("readr", "tidyr", "dplyr", "ckanr"))
          install.packages(c("httr", "ndjson"))
        shell: Rscript {0}
      - name: Download the data
        run: Rscript get-data.R
      - name: Commit Results
        run: |
          git add data/*.csv
          git commit -am "Data updated" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
          