# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: Get Data

on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
   workflow_dispatch

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up R
        uses: r-lib/actions/setup-r@v1
      - name: Install packages 
        run: |
          install.packages(c("readr", "dplyr", "ckanr"))
        shell: Rscript {0}
      - name: Download the data
        run: Rscript get-data.R
      - name: Commit Results
        run: |
          git add data/*.csv
          git commit -am "Data updated" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
          